/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QGraphicsView *graphicsView;
    QLabel *P1STitle;
    QLabel *P1_Stone;
    QLabel *label_3;
    QLabel *P1_Army;
    QLabel *label_5;
    QLabel *P1_Gold;
    QLabel *Player1Title;
    QLabel *Player2Title;
    QLabel *P2_Stone;
    QLabel *P2_Army;
    QLabel *P2_Gold;
    QLabel *P2GTitle;
    QLabel *P2ATitle;
    QLabel *P2STitle;
    QPushButton *pushButton;
    QPushButton *BuildCastle;
    QLabel *P1CTitle;
    QLabel *P1_VPoints;
    QLabel *P2CTitle;
    QLabel *P2_VPoints;
    QPushButton *EndTurnButton;
    QLabel *T1STitle;
    QLabel *T1ATitle;
    QLabel *T1GTitle;
    QLineEdit *Tile1_Stone;
    QLineEdit *Tile1_Army;
    QLineEdit *Tile1_Gold;
    QLabel *T7GTitle;
    QLabel *T7STitle;
    QLineEdit *Tile7_Stone;
    QLabel *T7ATitle;
    QLineEdit *Tile7_Gold;
    QLineEdit *Tile7_Army;
    QLabel *T8GTitle;
    QLabel *T8STitle;
    QLineEdit *Tile8_Stone;
    QLabel *T8ATitle;
    QLineEdit *Tile8_Gold;
    QLineEdit *Tile8_Army;
    QLabel *T3GTitle;
    QLabel *T3STitle;
    QLineEdit *Tile3_Stone;
    QLabel *T3ATitle;
    QLineEdit *Tile3_Gold;
    QLineEdit *Tile3_Army;
    QLabel *T2GTitle;
    QLabel *T2STitle;
    QLineEdit *Tile2_Stone;
    QLabel *T2ATitle;
    QLineEdit *Tile2_Gold;
    QLineEdit *Tile4_Army;
    QLabel *T4GTitle;
    QLabel *T4STitle;
    QLineEdit *Tile4_Stone;
    QLabel *T4ATitle;
    QLineEdit *Tile4_Gold;
    QLineEdit *Tile2_Army;
    QLabel *T5GTitle;
    QLabel *T5STitle;
    QLineEdit *Tile6_Army;
    QLabel *T6GTitle;
    QLineEdit *Tile6_Gold;
    QLineEdit *Tile5_Stone;
    QLineEdit *Tile6_Stone;
    QLabel *T5ATitle;
    QLabel *T6ATitle;
    QLineEdit *Tile5_Gold;
    QLabel *T6STitle;
    QLineEdit *Tile5_Army;
    QLabel *T12ATitle;
    QLineEdit *Tile12_Army;
    QLabel *T15STitle;
    QLineEdit *Tile11_Stone;
    QLineEdit *Tile9_Gold;
    QLabel *T16STitle;
    QLineEdit *Tile9_Army;
    QLineEdit *Tile15_Stone;
    QLabel *T10STitle;
    QLineEdit *Tile12_Stone;
    QLineEdit *Tile10_Stone;
    QLineEdit *Tile16_Army;
    QLabel *T14GTitle;
    QLabel *T12STitle;
    QLabel *T13GTitle;
    QLineEdit *Tile16_Stone;
    QLabel *T9ATitle;
    QLabel *T11STitle;
    QLabel *T9GTitle;
    QLineEdit *Tile9_Stone;
    QLineEdit *Tile14_Army;
    QLineEdit *Tile11_Gold;
    QLineEdit *Tile13_Army;
    QLineEdit *Tile10_Army;
    QLabel *T14STitle;
    QLabel *T15ATitle;
    QLineEdit *Tile16_Gold;
    QLabel *T10ATitle;
    QLineEdit *Tile15_Gold;
    QLineEdit *Tile10_Gold;
    QLabel *T10GTitle;
    QLabel *T13ATitle;
    QLineEdit *Tile15_Army;
    QLineEdit *Tile14_Gold;
    QLabel *T16ATitle;
    QLineEdit *Tile13_Gold;
    QLineEdit *Tile13_Stone;
    QLabel *T16GTitle;
    QLineEdit *Tile12_Gold;
    QLabel *T9STitle;
    QLabel *T13STitle;
    QLabel *T14ATitle;
    QLabel *T12GTitle;
    QLabel *T11GTitle;
    QLabel *T11ATitle;
    QLineEdit *Tile14_Stone;
    QLabel *T15GTitle;
    QLineEdit *Tile11_Army;
    QPushButton *BuyVPGoldButton;
    QLabel *Castle1;
    QLabel *Castle2;
    QLabel *Castle3;
    QLabel *Castle4;
    QLabel *Castle5;
    QLabel *Castle9;
    QLabel *Castle13;
    QLabel *Castle8;
    QLabel *Castle6;
    QLabel *Castle10;
    QLabel *Castle14;
    QLabel *Castle11;
    QLabel *Castle12;
    QLabel *Castle15;
    QLabel *Castle16;
    QLabel *Castle7;
    QPushButton *BuyVPArmyButton;
    QLabel *label;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1091, 818);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        graphicsView = new QGraphicsView(centralWidget);
        graphicsView->setObjectName(QString::fromUtf8("graphicsView"));
        graphicsView->setGeometry(QRect(0, 110, 831, 651));
        P1STitle = new QLabel(centralWidget);
        P1STitle->setObjectName(QString::fromUtf8("P1STitle"));
        P1STitle->setGeometry(QRect(10, 20, 41, 16));
        P1_Stone = new QLabel(centralWidget);
        P1_Stone->setObjectName(QString::fromUtf8("P1_Stone"));
        P1_Stone->setGeometry(QRect(50, 20, 31, 16));
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(10, 40, 41, 16));
        P1_Army = new QLabel(centralWidget);
        P1_Army->setObjectName(QString::fromUtf8("P1_Army"));
        P1_Army->setGeometry(QRect(50, 40, 31, 16));
        label_5 = new QLabel(centralWidget);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(10, 60, 31, 16));
        P1_Gold = new QLabel(centralWidget);
        P1_Gold->setObjectName(QString::fromUtf8("P1_Gold"));
        P1_Gold->setGeometry(QRect(50, 60, 31, 16));
        Player1Title = new QLabel(centralWidget);
        Player1Title->setObjectName(QString::fromUtf8("Player1Title"));
        Player1Title->setGeometry(QRect(20, 0, 57, 16));
        Player2Title = new QLabel(centralWidget);
        Player2Title->setObjectName(QString::fromUtf8("Player2Title"));
        Player2Title->setGeometry(QRect(120, 0, 61, 16));
        P2_Stone = new QLabel(centralWidget);
        P2_Stone->setObjectName(QString::fromUtf8("P2_Stone"));
        P2_Stone->setGeometry(QRect(150, 20, 57, 16));
        P2_Army = new QLabel(centralWidget);
        P2_Army->setObjectName(QString::fromUtf8("P2_Army"));
        P2_Army->setGeometry(QRect(150, 40, 41, 16));
        P2_Gold = new QLabel(centralWidget);
        P2_Gold->setObjectName(QString::fromUtf8("P2_Gold"));
        P2_Gold->setGeometry(QRect(150, 60, 41, 16));
        P2GTitle = new QLabel(centralWidget);
        P2GTitle->setObjectName(QString::fromUtf8("P2GTitle"));
        P2GTitle->setGeometry(QRect(110, 60, 31, 16));
        P2ATitle = new QLabel(centralWidget);
        P2ATitle->setObjectName(QString::fromUtf8("P2ATitle"));
        P2ATitle->setGeometry(QRect(110, 40, 41, 16));
        P2STitle = new QLabel(centralWidget);
        P2STitle->setObjectName(QString::fromUtf8("P2STitle"));
        P2STitle->setGeometry(QRect(110, 20, 41, 16));
        pushButton = new QPushButton(centralWidget);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(420, 10, 151, 71));
        BuildCastle = new QPushButton(centralWidget);
        BuildCastle->setObjectName(QString::fromUtf8("BuildCastle"));
        BuildCastle->setGeometry(QRect(220, 10, 161, 81));
        P1CTitle = new QLabel(centralWidget);
        P1CTitle->setObjectName(QString::fromUtf8("P1CTitle"));
        P1CTitle->setGeometry(QRect(5, 80, 71, 16));
        P1_VPoints = new QLabel(centralWidget);
        P1_VPoints->setObjectName(QString::fromUtf8("P1_VPoints"));
        P1_VPoints->setGeometry(QRect(70, 80, 21, 16));
        P2CTitle = new QLabel(centralWidget);
        P2CTitle->setObjectName(QString::fromUtf8("P2CTitle"));
        P2CTitle->setGeometry(QRect(110, 80, 71, 16));
        P2_VPoints = new QLabel(centralWidget);
        P2_VPoints->setObjectName(QString::fromUtf8("P2_VPoints"));
        P2_VPoints->setGeometry(QRect(180, 80, 16, 16));
        EndTurnButton = new QPushButton(centralWidget);
        EndTurnButton->setObjectName(QString::fromUtf8("EndTurnButton"));
        EndTurnButton->setGeometry(QRect(630, 10, 151, 71));
        T1STitle = new QLabel(centralWidget);
        T1STitle->setObjectName(QString::fromUtf8("T1STitle"));
        T1STitle->setGeometry(QRect(10, 120, 16, 16));
        T1ATitle = new QLabel(centralWidget);
        T1ATitle->setObjectName(QString::fromUtf8("T1ATitle"));
        T1ATitle->setGeometry(QRect(10, 140, 16, 16));
        T1GTitle = new QLabel(centralWidget);
        T1GTitle->setObjectName(QString::fromUtf8("T1GTitle"));
        T1GTitle->setGeometry(QRect(10, 160, 21, 16));
        Tile1_Stone = new QLineEdit(centralWidget);
        Tile1_Stone->setObjectName(QString::fromUtf8("Tile1_Stone"));
        Tile1_Stone->setGeometry(QRect(30, 120, 21, 21));
        Tile1_Army = new QLineEdit(centralWidget);
        Tile1_Army->setObjectName(QString::fromUtf8("Tile1_Army"));
        Tile1_Army->setGeometry(QRect(30, 140, 21, 21));
        Tile1_Gold = new QLineEdit(centralWidget);
        Tile1_Gold->setObjectName(QString::fromUtf8("Tile1_Gold"));
        Tile1_Gold->setGeometry(QRect(30, 160, 21, 21));
        T7GTitle = new QLabel(centralWidget);
        T7GTitle->setObjectName(QString::fromUtf8("T7GTitle"));
        T7GTitle->setGeometry(QRect(430, 320, 21, 16));
        T7STitle = new QLabel(centralWidget);
        T7STitle->setObjectName(QString::fromUtf8("T7STitle"));
        T7STitle->setGeometry(QRect(430, 280, 16, 16));
        Tile7_Stone = new QLineEdit(centralWidget);
        Tile7_Stone->setObjectName(QString::fromUtf8("Tile7_Stone"));
        Tile7_Stone->setGeometry(QRect(450, 280, 21, 21));
        T7ATitle = new QLabel(centralWidget);
        T7ATitle->setObjectName(QString::fromUtf8("T7ATitle"));
        T7ATitle->setGeometry(QRect(430, 300, 21, 16));
        Tile7_Gold = new QLineEdit(centralWidget);
        Tile7_Gold->setObjectName(QString::fromUtf8("Tile7_Gold"));
        Tile7_Gold->setGeometry(QRect(450, 320, 21, 21));
        Tile7_Army = new QLineEdit(centralWidget);
        Tile7_Army->setObjectName(QString::fromUtf8("Tile7_Army"));
        Tile7_Army->setGeometry(QRect(450, 300, 21, 21));
        T8GTitle = new QLabel(centralWidget);
        T8GTitle->setObjectName(QString::fromUtf8("T8GTitle"));
        T8GTitle->setGeometry(QRect(640, 320, 21, 16));
        T8STitle = new QLabel(centralWidget);
        T8STitle->setObjectName(QString::fromUtf8("T8STitle"));
        T8STitle->setGeometry(QRect(640, 280, 16, 16));
        Tile8_Stone = new QLineEdit(centralWidget);
        Tile8_Stone->setObjectName(QString::fromUtf8("Tile8_Stone"));
        Tile8_Stone->setGeometry(QRect(660, 280, 21, 21));
        T8ATitle = new QLabel(centralWidget);
        T8ATitle->setObjectName(QString::fromUtf8("T8ATitle"));
        T8ATitle->setGeometry(QRect(640, 300, 16, 16));
        Tile8_Gold = new QLineEdit(centralWidget);
        Tile8_Gold->setObjectName(QString::fromUtf8("Tile8_Gold"));
        Tile8_Gold->setGeometry(QRect(660, 320, 21, 21));
        Tile8_Army = new QLineEdit(centralWidget);
        Tile8_Army->setObjectName(QString::fromUtf8("Tile8_Army"));
        Tile8_Army->setGeometry(QRect(660, 300, 21, 21));
        T3GTitle = new QLabel(centralWidget);
        T3GTitle->setObjectName(QString::fromUtf8("T3GTitle"));
        T3GTitle->setGeometry(QRect(430, 160, 21, 16));
        T3STitle = new QLabel(centralWidget);
        T3STitle->setObjectName(QString::fromUtf8("T3STitle"));
        T3STitle->setGeometry(QRect(430, 120, 16, 16));
        Tile3_Stone = new QLineEdit(centralWidget);
        Tile3_Stone->setObjectName(QString::fromUtf8("Tile3_Stone"));
        Tile3_Stone->setGeometry(QRect(450, 120, 21, 21));
        T3ATitle = new QLabel(centralWidget);
        T3ATitle->setObjectName(QString::fromUtf8("T3ATitle"));
        T3ATitle->setGeometry(QRect(430, 140, 16, 16));
        Tile3_Gold = new QLineEdit(centralWidget);
        Tile3_Gold->setObjectName(QString::fromUtf8("Tile3_Gold"));
        Tile3_Gold->setGeometry(QRect(450, 160, 21, 21));
        Tile3_Army = new QLineEdit(centralWidget);
        Tile3_Army->setObjectName(QString::fromUtf8("Tile3_Army"));
        Tile3_Army->setGeometry(QRect(450, 140, 21, 21));
        T2GTitle = new QLabel(centralWidget);
        T2GTitle->setObjectName(QString::fromUtf8("T2GTitle"));
        T2GTitle->setGeometry(QRect(220, 160, 21, 16));
        T2STitle = new QLabel(centralWidget);
        T2STitle->setObjectName(QString::fromUtf8("T2STitle"));
        T2STitle->setGeometry(QRect(220, 120, 16, 16));
        Tile2_Stone = new QLineEdit(centralWidget);
        Tile2_Stone->setObjectName(QString::fromUtf8("Tile2_Stone"));
        Tile2_Stone->setGeometry(QRect(240, 120, 21, 21));
        T2ATitle = new QLabel(centralWidget);
        T2ATitle->setObjectName(QString::fromUtf8("T2ATitle"));
        T2ATitle->setGeometry(QRect(220, 140, 16, 16));
        Tile2_Gold = new QLineEdit(centralWidget);
        Tile2_Gold->setObjectName(QString::fromUtf8("Tile2_Gold"));
        Tile2_Gold->setGeometry(QRect(240, 160, 21, 21));
        Tile4_Army = new QLineEdit(centralWidget);
        Tile4_Army->setObjectName(QString::fromUtf8("Tile4_Army"));
        Tile4_Army->setGeometry(QRect(660, 140, 31, 21));
        T4GTitle = new QLabel(centralWidget);
        T4GTitle->setObjectName(QString::fromUtf8("T4GTitle"));
        T4GTitle->setGeometry(QRect(640, 160, 21, 16));
        T4STitle = new QLabel(centralWidget);
        T4STitle->setObjectName(QString::fromUtf8("T4STitle"));
        T4STitle->setGeometry(QRect(640, 120, 16, 16));
        Tile4_Stone = new QLineEdit(centralWidget);
        Tile4_Stone->setObjectName(QString::fromUtf8("Tile4_Stone"));
        Tile4_Stone->setGeometry(QRect(660, 120, 31, 21));
        T4ATitle = new QLabel(centralWidget);
        T4ATitle->setObjectName(QString::fromUtf8("T4ATitle"));
        T4ATitle->setGeometry(QRect(640, 140, 21, 16));
        Tile4_Gold = new QLineEdit(centralWidget);
        Tile4_Gold->setObjectName(QString::fromUtf8("Tile4_Gold"));
        Tile4_Gold->setGeometry(QRect(660, 160, 31, 21));
        Tile2_Army = new QLineEdit(centralWidget);
        Tile2_Army->setObjectName(QString::fromUtf8("Tile2_Army"));
        Tile2_Army->setGeometry(QRect(240, 140, 21, 21));
        T5GTitle = new QLabel(centralWidget);
        T5GTitle->setObjectName(QString::fromUtf8("T5GTitle"));
        T5GTitle->setGeometry(QRect(10, 320, 21, 16));
        T5STitle = new QLabel(centralWidget);
        T5STitle->setObjectName(QString::fromUtf8("T5STitle"));
        T5STitle->setGeometry(QRect(10, 280, 16, 16));
        Tile6_Army = new QLineEdit(centralWidget);
        Tile6_Army->setObjectName(QString::fromUtf8("Tile6_Army"));
        Tile6_Army->setGeometry(QRect(240, 300, 21, 21));
        T6GTitle = new QLabel(centralWidget);
        T6GTitle->setObjectName(QString::fromUtf8("T6GTitle"));
        T6GTitle->setGeometry(QRect(220, 320, 21, 16));
        Tile6_Gold = new QLineEdit(centralWidget);
        Tile6_Gold->setObjectName(QString::fromUtf8("Tile6_Gold"));
        Tile6_Gold->setGeometry(QRect(240, 320, 21, 21));
        Tile5_Stone = new QLineEdit(centralWidget);
        Tile5_Stone->setObjectName(QString::fromUtf8("Tile5_Stone"));
        Tile5_Stone->setGeometry(QRect(30, 280, 21, 21));
        Tile6_Stone = new QLineEdit(centralWidget);
        Tile6_Stone->setObjectName(QString::fromUtf8("Tile6_Stone"));
        Tile6_Stone->setGeometry(QRect(240, 280, 21, 21));
        T5ATitle = new QLabel(centralWidget);
        T5ATitle->setObjectName(QString::fromUtf8("T5ATitle"));
        T5ATitle->setGeometry(QRect(10, 300, 16, 16));
        T6ATitle = new QLabel(centralWidget);
        T6ATitle->setObjectName(QString::fromUtf8("T6ATitle"));
        T6ATitle->setGeometry(QRect(220, 300, 16, 16));
        Tile5_Gold = new QLineEdit(centralWidget);
        Tile5_Gold->setObjectName(QString::fromUtf8("Tile5_Gold"));
        Tile5_Gold->setGeometry(QRect(30, 320, 21, 21));
        T6STitle = new QLabel(centralWidget);
        T6STitle->setObjectName(QString::fromUtf8("T6STitle"));
        T6STitle->setGeometry(QRect(220, 280, 16, 16));
        Tile5_Army = new QLineEdit(centralWidget);
        Tile5_Army->setObjectName(QString::fromUtf8("Tile5_Army"));
        Tile5_Army->setGeometry(QRect(30, 300, 21, 21));
        T12ATitle = new QLabel(centralWidget);
        T12ATitle->setObjectName(QString::fromUtf8("T12ATitle"));
        T12ATitle->setGeometry(QRect(640, 460, 21, 16));
        Tile12_Army = new QLineEdit(centralWidget);
        Tile12_Army->setObjectName(QString::fromUtf8("Tile12_Army"));
        Tile12_Army->setGeometry(QRect(660, 460, 21, 21));
        T15STitle = new QLabel(centralWidget);
        T15STitle->setObjectName(QString::fromUtf8("T15STitle"));
        T15STitle->setGeometry(QRect(430, 600, 16, 16));
        Tile11_Stone = new QLineEdit(centralWidget);
        Tile11_Stone->setObjectName(QString::fromUtf8("Tile11_Stone"));
        Tile11_Stone->setGeometry(QRect(450, 440, 21, 21));
        Tile9_Gold = new QLineEdit(centralWidget);
        Tile9_Gold->setObjectName(QString::fromUtf8("Tile9_Gold"));
        Tile9_Gold->setGeometry(QRect(30, 480, 21, 21));
        T16STitle = new QLabel(centralWidget);
        T16STitle->setObjectName(QString::fromUtf8("T16STitle"));
        T16STitle->setGeometry(QRect(640, 600, 16, 16));
        Tile9_Army = new QLineEdit(centralWidget);
        Tile9_Army->setObjectName(QString::fromUtf8("Tile9_Army"));
        Tile9_Army->setGeometry(QRect(30, 460, 21, 21));
        Tile15_Stone = new QLineEdit(centralWidget);
        Tile15_Stone->setObjectName(QString::fromUtf8("Tile15_Stone"));
        Tile15_Stone->setGeometry(QRect(450, 600, 21, 21));
        T10STitle = new QLabel(centralWidget);
        T10STitle->setObjectName(QString::fromUtf8("T10STitle"));
        T10STitle->setGeometry(QRect(220, 440, 16, 16));
        Tile12_Stone = new QLineEdit(centralWidget);
        Tile12_Stone->setObjectName(QString::fromUtf8("Tile12_Stone"));
        Tile12_Stone->setGeometry(QRect(660, 440, 21, 21));
        Tile10_Stone = new QLineEdit(centralWidget);
        Tile10_Stone->setObjectName(QString::fromUtf8("Tile10_Stone"));
        Tile10_Stone->setGeometry(QRect(240, 440, 21, 21));
        Tile16_Army = new QLineEdit(centralWidget);
        Tile16_Army->setObjectName(QString::fromUtf8("Tile16_Army"));
        Tile16_Army->setGeometry(QRect(660, 620, 21, 21));
        T14GTitle = new QLabel(centralWidget);
        T14GTitle->setObjectName(QString::fromUtf8("T14GTitle"));
        T14GTitle->setGeometry(QRect(220, 640, 21, 16));
        T12STitle = new QLabel(centralWidget);
        T12STitle->setObjectName(QString::fromUtf8("T12STitle"));
        T12STitle->setGeometry(QRect(640, 440, 16, 16));
        T13GTitle = new QLabel(centralWidget);
        T13GTitle->setObjectName(QString::fromUtf8("T13GTitle"));
        T13GTitle->setGeometry(QRect(10, 640, 21, 16));
        Tile16_Stone = new QLineEdit(centralWidget);
        Tile16_Stone->setObjectName(QString::fromUtf8("Tile16_Stone"));
        Tile16_Stone->setGeometry(QRect(660, 600, 21, 21));
        T9ATitle = new QLabel(centralWidget);
        T9ATitle->setObjectName(QString::fromUtf8("T9ATitle"));
        T9ATitle->setGeometry(QRect(10, 460, 16, 16));
        T11STitle = new QLabel(centralWidget);
        T11STitle->setObjectName(QString::fromUtf8("T11STitle"));
        T11STitle->setGeometry(QRect(430, 440, 16, 16));
        T9GTitle = new QLabel(centralWidget);
        T9GTitle->setObjectName(QString::fromUtf8("T9GTitle"));
        T9GTitle->setGeometry(QRect(10, 480, 21, 16));
        Tile9_Stone = new QLineEdit(centralWidget);
        Tile9_Stone->setObjectName(QString::fromUtf8("Tile9_Stone"));
        Tile9_Stone->setGeometry(QRect(30, 440, 21, 21));
        Tile14_Army = new QLineEdit(centralWidget);
        Tile14_Army->setObjectName(QString::fromUtf8("Tile14_Army"));
        Tile14_Army->setGeometry(QRect(240, 620, 21, 21));
        Tile11_Gold = new QLineEdit(centralWidget);
        Tile11_Gold->setObjectName(QString::fromUtf8("Tile11_Gold"));
        Tile11_Gold->setGeometry(QRect(450, 480, 21, 21));
        Tile13_Army = new QLineEdit(centralWidget);
        Tile13_Army->setObjectName(QString::fromUtf8("Tile13_Army"));
        Tile13_Army->setGeometry(QRect(30, 620, 31, 21));
        Tile10_Army = new QLineEdit(centralWidget);
        Tile10_Army->setObjectName(QString::fromUtf8("Tile10_Army"));
        Tile10_Army->setGeometry(QRect(240, 460, 21, 21));
        T14STitle = new QLabel(centralWidget);
        T14STitle->setObjectName(QString::fromUtf8("T14STitle"));
        T14STitle->setGeometry(QRect(220, 600, 16, 16));
        T15ATitle = new QLabel(centralWidget);
        T15ATitle->setObjectName(QString::fromUtf8("T15ATitle"));
        T15ATitle->setGeometry(QRect(430, 620, 21, 16));
        Tile16_Gold = new QLineEdit(centralWidget);
        Tile16_Gold->setObjectName(QString::fromUtf8("Tile16_Gold"));
        Tile16_Gold->setGeometry(QRect(660, 640, 21, 21));
        T10ATitle = new QLabel(centralWidget);
        T10ATitle->setObjectName(QString::fromUtf8("T10ATitle"));
        T10ATitle->setGeometry(QRect(220, 460, 16, 16));
        Tile15_Gold = new QLineEdit(centralWidget);
        Tile15_Gold->setObjectName(QString::fromUtf8("Tile15_Gold"));
        Tile15_Gold->setGeometry(QRect(450, 640, 21, 21));
        Tile10_Gold = new QLineEdit(centralWidget);
        Tile10_Gold->setObjectName(QString::fromUtf8("Tile10_Gold"));
        Tile10_Gold->setGeometry(QRect(240, 480, 21, 21));
        T10GTitle = new QLabel(centralWidget);
        T10GTitle->setObjectName(QString::fromUtf8("T10GTitle"));
        T10GTitle->setGeometry(QRect(220, 480, 21, 16));
        T13ATitle = new QLabel(centralWidget);
        T13ATitle->setObjectName(QString::fromUtf8("T13ATitle"));
        T13ATitle->setGeometry(QRect(10, 620, 16, 16));
        Tile15_Army = new QLineEdit(centralWidget);
        Tile15_Army->setObjectName(QString::fromUtf8("Tile15_Army"));
        Tile15_Army->setGeometry(QRect(450, 620, 21, 21));
        Tile14_Gold = new QLineEdit(centralWidget);
        Tile14_Gold->setObjectName(QString::fromUtf8("Tile14_Gold"));
        Tile14_Gold->setGeometry(QRect(240, 640, 21, 21));
        T16ATitle = new QLabel(centralWidget);
        T16ATitle->setObjectName(QString::fromUtf8("T16ATitle"));
        T16ATitle->setGeometry(QRect(640, 620, 16, 16));
        Tile13_Gold = new QLineEdit(centralWidget);
        Tile13_Gold->setObjectName(QString::fromUtf8("Tile13_Gold"));
        Tile13_Gold->setGeometry(QRect(30, 640, 31, 21));
        Tile13_Stone = new QLineEdit(centralWidget);
        Tile13_Stone->setObjectName(QString::fromUtf8("Tile13_Stone"));
        Tile13_Stone->setGeometry(QRect(30, 600, 31, 21));
        T16GTitle = new QLabel(centralWidget);
        T16GTitle->setObjectName(QString::fromUtf8("T16GTitle"));
        T16GTitle->setGeometry(QRect(640, 640, 21, 16));
        Tile12_Gold = new QLineEdit(centralWidget);
        Tile12_Gold->setObjectName(QString::fromUtf8("Tile12_Gold"));
        Tile12_Gold->setGeometry(QRect(660, 480, 21, 21));
        T9STitle = new QLabel(centralWidget);
        T9STitle->setObjectName(QString::fromUtf8("T9STitle"));
        T9STitle->setGeometry(QRect(10, 440, 16, 16));
        T13STitle = new QLabel(centralWidget);
        T13STitle->setObjectName(QString::fromUtf8("T13STitle"));
        T13STitle->setGeometry(QRect(10, 600, 16, 16));
        T14ATitle = new QLabel(centralWidget);
        T14ATitle->setObjectName(QString::fromUtf8("T14ATitle"));
        T14ATitle->setGeometry(QRect(220, 620, 16, 16));
        T12GTitle = new QLabel(centralWidget);
        T12GTitle->setObjectName(QString::fromUtf8("T12GTitle"));
        T12GTitle->setGeometry(QRect(640, 480, 21, 16));
        T11GTitle = new QLabel(centralWidget);
        T11GTitle->setObjectName(QString::fromUtf8("T11GTitle"));
        T11GTitle->setGeometry(QRect(430, 480, 21, 16));
        T11ATitle = new QLabel(centralWidget);
        T11ATitle->setObjectName(QString::fromUtf8("T11ATitle"));
        T11ATitle->setGeometry(QRect(430, 460, 16, 16));
        Tile14_Stone = new QLineEdit(centralWidget);
        Tile14_Stone->setObjectName(QString::fromUtf8("Tile14_Stone"));
        Tile14_Stone->setGeometry(QRect(240, 600, 21, 21));
        T15GTitle = new QLabel(centralWidget);
        T15GTitle->setObjectName(QString::fromUtf8("T15GTitle"));
        T15GTitle->setGeometry(QRect(430, 640, 21, 16));
        Tile11_Army = new QLineEdit(centralWidget);
        Tile11_Army->setObjectName(QString::fromUtf8("Tile11_Army"));
        Tile11_Army->setGeometry(QRect(450, 460, 21, 21));
        BuyVPGoldButton = new QPushButton(centralWidget);
        BuyVPGoldButton->setObjectName(QString::fromUtf8("BuyVPGoldButton"));
        BuyVPGoldButton->setGeometry(QRect(870, 20, 181, 81));
        Castle1 = new QLabel(centralWidget);
        Castle1->setObjectName(QString::fromUtf8("Castle1"));
        Castle1->setGeometry(QRect(90, 160, 71, 21));
        QFont font;
        font.setFamily(QString::fromUtf8("Arial Rounded MT Bold"));
        font.setPointSize(18);
        Castle1->setFont(font);
        Castle2 = new QLabel(centralWidget);
        Castle2->setObjectName(QString::fromUtf8("Castle2"));
        Castle2->setGeometry(QRect(290, 160, 71, 21));
        Castle2->setFont(font);
        Castle3 = new QLabel(centralWidget);
        Castle3->setObjectName(QString::fromUtf8("Castle3"));
        Castle3->setGeometry(QRect(490, 160, 71, 21));
        Castle3->setFont(font);
        Castle4 = new QLabel(centralWidget);
        Castle4->setObjectName(QString::fromUtf8("Castle4"));
        Castle4->setGeometry(QRect(700, 160, 71, 21));
        Castle4->setFont(font);
        Castle5 = new QLabel(centralWidget);
        Castle5->setObjectName(QString::fromUtf8("Castle5"));
        Castle5->setGeometry(QRect(70, 320, 71, 21));
        Castle5->setFont(font);
        Castle9 = new QLabel(centralWidget);
        Castle9->setObjectName(QString::fromUtf8("Castle9"));
        Castle9->setGeometry(QRect(70, 480, 71, 21));
        Castle9->setFont(font);
        Castle13 = new QLabel(centralWidget);
        Castle13->setObjectName(QString::fromUtf8("Castle13"));
        Castle13->setGeometry(QRect(70, 640, 71, 21));
        Castle13->setFont(font);
        Castle8 = new QLabel(centralWidget);
        Castle8->setObjectName(QString::fromUtf8("Castle8"));
        Castle8->setGeometry(QRect(710, 320, 71, 21));
        Castle8->setFont(font);
        Castle6 = new QLabel(centralWidget);
        Castle6->setObjectName(QString::fromUtf8("Castle6"));
        Castle6->setGeometry(QRect(290, 330, 71, 21));
        Castle6->setFont(font);
        Castle10 = new QLabel(centralWidget);
        Castle10->setObjectName(QString::fromUtf8("Castle10"));
        Castle10->setGeometry(QRect(290, 480, 71, 21));
        Castle10->setFont(font);
        Castle14 = new QLabel(centralWidget);
        Castle14->setObjectName(QString::fromUtf8("Castle14"));
        Castle14->setGeometry(QRect(280, 640, 71, 21));
        Castle14->setFont(font);
        Castle11 = new QLabel(centralWidget);
        Castle11->setObjectName(QString::fromUtf8("Castle11"));
        Castle11->setGeometry(QRect(500, 480, 71, 21));
        Castle11->setFont(font);
        Castle12 = new QLabel(centralWidget);
        Castle12->setObjectName(QString::fromUtf8("Castle12"));
        Castle12->setGeometry(QRect(710, 480, 71, 21));
        Castle12->setFont(font);
        Castle15 = new QLabel(centralWidget);
        Castle15->setObjectName(QString::fromUtf8("Castle15"));
        Castle15->setGeometry(QRect(500, 640, 71, 21));
        Castle15->setFont(font);
        Castle16 = new QLabel(centralWidget);
        Castle16->setObjectName(QString::fromUtf8("Castle16"));
        Castle16->setGeometry(QRect(710, 640, 71, 21));
        Castle16->setFont(font);
        Castle7 = new QLabel(centralWidget);
        Castle7->setObjectName(QString::fromUtf8("Castle7"));
        Castle7->setGeometry(QRect(500, 320, 71, 21));
        Castle7->setFont(font);
        BuyVPArmyButton = new QPushButton(centralWidget);
        BuyVPArmyButton->setObjectName(QString::fromUtf8("BuyVPArmyButton"));
        BuyVPArmyButton->setGeometry(QRect(870, 120, 181, 81));
        label = new QLabel(centralWidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(230, 90, 131, 16));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1091, 22));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        P1STitle->setText(QApplication::translate("MainWindow", "Stone:", nullptr));
        P1_Stone->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_3->setText(QApplication::translate("MainWindow", "Army:", nullptr));
        P1_Army->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_5->setText(QApplication::translate("MainWindow", "Gold:", nullptr));
        P1_Gold->setText(QApplication::translate("MainWindow", "0", nullptr));
        Player1Title->setText(QApplication::translate("MainWindow", "Player 1", nullptr));
        Player2Title->setText(QApplication::translate("MainWindow", "Player 2", nullptr));
        P2_Stone->setText(QApplication::translate("MainWindow", "0", nullptr));
        P2_Army->setText(QApplication::translate("MainWindow", "0", nullptr));
        P2_Gold->setText(QApplication::translate("MainWindow", "0", nullptr));
        P2GTitle->setText(QApplication::translate("MainWindow", "Gold:", nullptr));
        P2ATitle->setText(QApplication::translate("MainWindow", "Army:", nullptr));
        P2STitle->setText(QApplication::translate("MainWindow", "Stone:", nullptr));
        pushButton->setText(QApplication::translate("MainWindow", "Battle", nullptr));
        BuildCastle->setText(QApplication::translate("MainWindow", "Build Castle", nullptr));
        P1CTitle->setText(QApplication::translate("MainWindow", "V Points:", nullptr));
        P1_VPoints->setText(QApplication::translate("MainWindow", "0", nullptr));
        P2CTitle->setText(QApplication::translate("MainWindow", "V Points:", nullptr));
        P2_VPoints->setText(QApplication::translate("MainWindow", "0", nullptr));
        EndTurnButton->setText(QApplication::translate("MainWindow", "End Turn", nullptr));
        T1STitle->setText(QApplication::translate("MainWindow", "S:", nullptr));
        T1ATitle->setText(QApplication::translate("MainWindow", "A:", nullptr));
        T1GTitle->setText(QApplication::translate("MainWindow", "G:", nullptr));
        T7GTitle->setText(QApplication::translate("MainWindow", "G:", nullptr));
        T7STitle->setText(QApplication::translate("MainWindow", "S:", nullptr));
        T7ATitle->setText(QApplication::translate("MainWindow", "A:", nullptr));
        T8GTitle->setText(QApplication::translate("MainWindow", "G:", nullptr));
        T8STitle->setText(QApplication::translate("MainWindow", "S:", nullptr));
        T8ATitle->setText(QApplication::translate("MainWindow", "A:", nullptr));
        T3GTitle->setText(QApplication::translate("MainWindow", "G:", nullptr));
        T3STitle->setText(QApplication::translate("MainWindow", "S:", nullptr));
        T3ATitle->setText(QApplication::translate("MainWindow", "A:", nullptr));
        T2GTitle->setText(QApplication::translate("MainWindow", "G:", nullptr));
        T2STitle->setText(QApplication::translate("MainWindow", "S:", nullptr));
        T2ATitle->setText(QApplication::translate("MainWindow", "A:", nullptr));
        T4GTitle->setText(QApplication::translate("MainWindow", "G:", nullptr));
        T4STitle->setText(QApplication::translate("MainWindow", "S:", nullptr));
        T4ATitle->setText(QApplication::translate("MainWindow", "A:", nullptr));
        T5GTitle->setText(QApplication::translate("MainWindow", "G:", nullptr));
        T5STitle->setText(QApplication::translate("MainWindow", "S:", nullptr));
        T6GTitle->setText(QApplication::translate("MainWindow", "G:", nullptr));
        T5ATitle->setText(QApplication::translate("MainWindow", "A:", nullptr));
        T6ATitle->setText(QApplication::translate("MainWindow", "A:", nullptr));
        T6STitle->setText(QApplication::translate("MainWindow", "S:", nullptr));
        T12ATitle->setText(QApplication::translate("MainWindow", "A:", nullptr));
        T15STitle->setText(QApplication::translate("MainWindow", "S:", nullptr));
        T16STitle->setText(QApplication::translate("MainWindow", "S:", nullptr));
        T10STitle->setText(QApplication::translate("MainWindow", "S:", nullptr));
        T14GTitle->setText(QApplication::translate("MainWindow", "G:", nullptr));
        T12STitle->setText(QApplication::translate("MainWindow", "S:", nullptr));
        T13GTitle->setText(QApplication::translate("MainWindow", "G:", nullptr));
        T9ATitle->setText(QApplication::translate("MainWindow", "A:", nullptr));
        T11STitle->setText(QApplication::translate("MainWindow", "S:", nullptr));
        T9GTitle->setText(QApplication::translate("MainWindow", "G:", nullptr));
        T14STitle->setText(QApplication::translate("MainWindow", "S:", nullptr));
        T15ATitle->setText(QApplication::translate("MainWindow", "A:", nullptr));
        T10ATitle->setText(QApplication::translate("MainWindow", "A:", nullptr));
        T10GTitle->setText(QApplication::translate("MainWindow", "G:", nullptr));
        T13ATitle->setText(QApplication::translate("MainWindow", "A:", nullptr));
        T16ATitle->setText(QApplication::translate("MainWindow", "A:", nullptr));
        T16GTitle->setText(QApplication::translate("MainWindow", "G:", nullptr));
        T9STitle->setText(QApplication::translate("MainWindow", "S:", nullptr));
        T13STitle->setText(QApplication::translate("MainWindow", "S:", nullptr));
        T14ATitle->setText(QApplication::translate("MainWindow", "A:", nullptr));
        T12GTitle->setText(QApplication::translate("MainWindow", "G:", nullptr));
        T11GTitle->setText(QApplication::translate("MainWindow", "G:", nullptr));
        T11ATitle->setText(QApplication::translate("MainWindow", "A:", nullptr));
        T15GTitle->setText(QApplication::translate("MainWindow", "G:", nullptr));
        BuyVPGoldButton->setText(QApplication::translate("MainWindow", "Victory Point (200 gold)", nullptr));
        Castle1->setText(QApplication::translate("MainWindow", "Castle", nullptr));
        Castle2->setText(QApplication::translate("MainWindow", "Castle", nullptr));
        Castle3->setText(QApplication::translate("MainWindow", "Castle", nullptr));
        Castle4->setText(QApplication::translate("MainWindow", "Castle", nullptr));
        Castle5->setText(QApplication::translate("MainWindow", "Castle", nullptr));
        Castle9->setText(QApplication::translate("MainWindow", "Castle", nullptr));
        Castle13->setText(QApplication::translate("MainWindow", "Castle", nullptr));
        Castle8->setText(QApplication::translate("MainWindow", "Castle", nullptr));
        Castle6->setText(QApplication::translate("MainWindow", "Castle", nullptr));
        Castle10->setText(QApplication::translate("MainWindow", "Castle", nullptr));
        Castle14->setText(QApplication::translate("MainWindow", "Castle", nullptr));
        Castle11->setText(QApplication::translate("MainWindow", "Castle", nullptr));
        Castle12->setText(QApplication::translate("MainWindow", "Castle", nullptr));
        Castle15->setText(QApplication::translate("MainWindow", "Castle", nullptr));
        Castle16->setText(QApplication::translate("MainWindow", "Castle", nullptr));
        Castle7->setText(QApplication::translate("MainWindow", "Castle", nullptr));
        BuyVPArmyButton->setText(QApplication::translate("MainWindow", "Victory Point (200 army)", nullptr));
        label->setText(QApplication::translate("MainWindow", "100 Gold & 100 Stone", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
